### ISSUE TITLE
Build fails at ruby 2.4.0

### ISSUE THREAD

**Issue by anatol** [wincent/wikitext#4]
```
Building native extensions.  This could take a while...
ERROR:  Error installing wikitext-4.3.gem:
	ERROR: Failed to build gem native extension.

    current directory: /build/ruby-wikitext/pkg/ruby-wikitext/usr/lib/ruby/gems/2.4.0/gems/wikitext-4.3/ext/wikitext
/usr/bin/ruby -r ./siteconf20170110-534-zys8cx.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
extconf.rb:32:in `<main>': unsupported Ruby version: 2.4.0 (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /build/ruby-wikitext/pkg/ruby-wikitext/usr/lib/ruby/gems/2.4.0/gems/wikitext-4.3 for inspection.
Results logged to /build/ruby-wikitext/pkg/ruby-wikitext/usr/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/wikitext-4.3/gem_make.out
```

The issue comes from here https://github.com/wincent/wikitext/blob/43e86ccd7b665afdde3cd332b2ba71fe6fa0b071/ext/wikitext/extconf.rb#L31 is similar to the last year with ruby 2.3. Is it possible to remove this version check at all?

**Comment by wincent** [comment]
We just need to verify that the gem still works under 2.4, then we can relax the check.

**Comment by wincent** [comment]
Thanks for reporting this @anatol. About to push the 4.4 version of the gem.

**Comment by anatol** [comment]
Having an artificial install restriction and preventing installing the gem at newer version of ruby is not typical. Out of ~500 gems installed at my system only `wikitext` has such restriction. I do not see why `wikitext` is so special here.

It neither convenient as users can't use the gem with newer ruby until upstream releases a new version.

Having such artificial install restrictions has no any benefit and should be removed.

**Comment by wincent** [comment]
Yes, it's not typical, but wikitext also does some not-typical low-level
struct access in the C extension in order to squeeze out additional
performance, but which may not be compatible across major Ruby versions and
which could segfault the running process, which would be a nasty failure
mode.

So, I prefer to maintain the manual verification step. The update process
is pretty minimal, this is a build time and not a runtime error, and Ruby
major release dates are predictable (every Christmas day in recent years),
so it would be easy enough to even do this in advance if anybody cared
enough to.
